/**
 * Canvas Manager — Agent-editable HTML canvas system.
 *
 * Inspired by OpenClaw A2UI. Allows the AI agent to create, edit, and
 * serve dynamic HTML pages as visual outputs. The agent can use the
 * `canvas_create` and `canvas_update` tools to generate dashboards,
 * charts, reports, interactive widgets, and more.
 *
 * Canvas files are served at `/__evoclaw__/canvas/<name>` and support
 * full HTML/CSS/JS including inline scripts, external CDN resources,
 * and EvoClaw API proxy for live data.
 */

import * as fs from "fs";
import * as path from "path";
import * as crypto from "crypto";
import { atomicWriteFileSync } from "./atomic-write";

export interface CanvasConfig {
  /** Directory to store canvas files (default: "data/canvas") */
  storagePath?: string;
  /** Maximum canvas file size in bytes (default: 5MB) */
  maxFileSize?: number;
  /** Maximum number of canvas files (default: 100) */
  maxFiles?: number;
  /** Whether to enable the canvas API endpoints */
  enabled?: boolean;
  /** Allowed CDN origins for script/style resources */
  allowedCDNs?: string[];
}

export interface CanvasFile {
  /** Unique canvas identifier (slug) */
  id: string;
  /** Display title */
  title: string;
  /** HTML content */
  html: string;
  /** Created timestamp */
  createdAt: string;
  /** Last modified timestamp */
  updatedAt: string;
  /** Creator (agent or user) */
  createdBy: "agent" | "user";
  /** Optional tags for organization */
  tags?: string[];
  /** Optional description */
  description?: string;
  /** Whether this canvas is publicly accessible (no auth) */
  public?: boolean;
}

export interface CanvasListResult {
  canvases: Array<{
    id: string;
    title: string;
    description?: string;
    tags?: string[];
    createdAt: string;
    updatedAt: string;
    createdBy: string;
    public: boolean;
    size: number;
  }>;
  total: number;
  storageUsed: number;
  maxFiles: number;
}

const DEFAULT_CDN_WHITELIST = [
  "cdn.jsdelivr.net",
  "unpkg.com",
  "cdnjs.cloudflare.com",
  "cdn.plot.ly",
  "d3js.org",
  "cdn.tailwindcss.com",
  "cdn.jsdelivr.net/npm/chart.js",
];

const CANVAS_TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{title}}</title>
  <style>
    :root {
      --bg: #0f172a;
      --card: #1e293b;
      --text: #e2e8f0;
      --accent: #3b82f6;
      --border: #334155;
      --success: #22c55e;
      --warning: #f59e0b;
      --danger: #ef4444;
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      background: var(--bg);
      color: var(--text);
      min-height: 100vh;
      padding: 2rem;
    }
    .canvas-header {
      text-align: center;
      margin-bottom: 2rem;
      padding: 2rem;
      background: var(--card);
      border-radius: 12px;
      border: 1px solid var(--border);
    }
    .canvas-header h1 { font-size: 2rem; color: var(--accent); }
    .canvas-header p { margin-top: 0.5rem; color: #94a3b8; }
    .canvas-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
      gap: 1.5rem;
    }
    .canvas-card {
      background: var(--card);
      border-radius: 12px;
      padding: 1.5rem;
      border: 1px solid var(--border);
      transition: transform 0.2s, box-shadow 0.2s;
    }
    .canvas-card:hover {
      transform: translateY(-2px);
      box-shadow: 0 8px 25px rgba(0,0,0,0.3);
    }
    .stat-value {
      font-size: 2.5rem;
      font-weight: 700;
      background: linear-gradient(135deg, var(--accent), #8b5cf6);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
    }
    .badge {
      display: inline-block;
      padding: 0.25rem 0.75rem;
      border-radius: 20px;
      font-size: 0.75rem;
      font-weight: 600;
    }
    .badge-success { background: rgba(34,197,94,0.2); color: var(--success); }
    .badge-warning { background: rgba(245,158,11,0.2); color: var(--warning); }
    .badge-danger { background: rgba(239,68,68,0.2); color: var(--danger); }
  </style>
</head>
<body>
  <div class="canvas-header">
    <h1>{{title}}</h1>
    <p>Generated by EvoClaw — {{timestamp}}</p>
  </div>
  <div class="canvas-grid" id="content">
    <!-- Agent content goes here -->
  </div>
</body>
</html>`;

const SANDBOX_POLICY = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline' 'unsafe-eval' cdn.jsdelivr.net unpkg.com cdnjs.cloudflare.com cdn.plot.ly d3js.org cdn.tailwindcss.com",
  "style-src 'self' 'unsafe-inline' cdn.jsdelivr.net unpkg.com cdnjs.cloudflare.com cdn.tailwindcss.com",
  "img-src 'self' data: https: http:",
  "connect-src 'self' https:",
  "font-src 'self' data:",
].join("; ");

export class CanvasManager {
  private config: Required<Omit<CanvasConfig, "allowedCDNs">> & { allowedCDNs: string[] };
  private indexPath: string;

  constructor(config: CanvasConfig = {}) {
    this.config = {
      storagePath: config.storagePath ?? "data/canvas",
      maxFileSize: config.maxFileSize ?? 5 * 1024 * 1024,
      maxFiles: config.maxFiles ?? 100,
      enabled: config.enabled ?? true,
      allowedCDNs: config.allowedCDNs ?? DEFAULT_CDN_WHITELIST,
    };

    this.indexPath = path.join(this.config.storagePath, "_index.json");
  }

  // ── Initialization ──────────────────────────────────────────────────

  initialize(): void {
    if (!this.config.enabled) return;

    try {
      fs.mkdirSync(this.config.storagePath, { recursive: true });

      if (!fs.existsSync(this.indexPath)) {
        this.writeIndex([]);
      }

      process.stdout.write(`[CanvasManager] Canvas storage at ${this.config.storagePath}`);
    } catch (err) {
      process.stderr.write(`[CanvasManager] Failed to initialize: ${err}`);
    }
  }

  // ── CRUD Operations ─────────────────────────────────────────────────

  /** List all canvases with metadata */
  listCanvases(): CanvasListResult {
    const canvases = this.readIndex();

    const totalSize = canvases.reduce((sum, c) => {
      try {
        const filePath = this.getFilePath(c.id);
        return sum + (fs.existsSync(filePath) ? fs.statSync(filePath).size : 0);
      } catch {
        return sum;
      }
    }, 0);

    return {
      canvases: canvases.map((c) => ({
        id: c.id,
        title: c.title,
        description: c.description,
        tags: c.tags,
        createdAt: c.createdAt,
        updatedAt: c.updatedAt,
        createdBy: c.createdBy,
        public: c.public ?? false,
        size: this.getFileSize(c.id),
      })),
      total: canvases.length,
      storageUsed: totalSize,
      maxFiles: this.config.maxFiles,
    };
  }

  /** Get a canvas by ID (metadata only) */
  getCanvas(id: string): CanvasFile | undefined {
    const canvases = this.readIndex();
    return canvases.find((c) => c.id === id);
  }

  /** Get the HTML content of a canvas */
  getCanvasHTML(id: string): string | null {
    const canvas = this.getCanvas(id);
    if (!canvas) return null;

    const filePath = this.getFilePath(id);
    try {
      if (fs.existsSync(filePath)) {
        return fs.readFileSync(filePath, "utf-8");
      }
      return canvas.html;
    } catch {
      return null;
    }
  }

  /**
   * Create a new canvas. The agent calls this with generated HTML.
   * Returns the canvas URL so the agent can tell the user where to view it.
   */
  createCanvas(
    title: string,
    html: string,
    options?: {
      id?: string;
      description?: string;
      tags?: string[];
      createdBy?: "agent" | "user";
      public?: boolean;
    }
  ): { canvas: CanvasFile; url: string } {
    if (!this.config.enabled) {
      throw new Error("Canvas system is disabled");
    }

    // Check limits
    const canvases = this.readIndex();
    if (canvases.length >= this.config.maxFiles) {
      throw new Error(`Maximum canvas count reached (${this.config.maxFiles})`);
    }
    if (Buffer.byteLength(html, "utf-8") > this.config.maxFileSize) {
      throw new Error(`Canvas exceeds maximum size (${this.config.maxFileSize} bytes)`);
    }

    // Sanitize HTML slightly — inject CSP meta tag
    html = this.sanitizeHTML(html);

    // Generate or use provided ID
    const id = options?.id ?? this.generateId(title);
    const now = new Date().toISOString();

    const canvas: CanvasFile = {
      id,
      title,
      html,
      createdAt: now,
      updatedAt: now,
      createdBy: options?.createdBy ?? "agent",
      tags: options?.tags ?? [],
      description: options?.description,
      public: options?.public ?? false,
    };

    // Write HTML file（原子写入，符合 AGENTS.md 规则）
    const filePath = this.getFilePath(id);
    atomicWriteFileSync(filePath, html);

    // Update index
    const existing = canvases.findIndex((c) => c.id === id);
    if (existing >= 0) {
      canvases[existing] = canvas;
    } else {
      canvases.push(canvas);
    }
    this.writeIndex(canvases);

    process.stdout.write(`[CanvasManager] ${existing >= 0 ? "Updated" : "Created"} canvas "${id}"`);

    return {
      canvas,
      url: `/__evoclaw__/canvas/${id}`,
    };
  }

  /**
   * Update an existing canvas. For partial HTML updates (e.g., the agent
   * wants to add a new section), use append mode.
   */
  updateCanvas(
    id: string,
    updates: {
      html?: string;
      title?: string;
      description?: string;
      tags?: string[];
      appendHTML?: string;
      public?: boolean;
    }
  ): CanvasFile | null {
    const canvases = this.readIndex();
    const index = canvases.findIndex((c) => c.id === id);
    if (index < 0) return null;

    const canvas = canvases[index];

    if (updates.html !== undefined) {
      if (Buffer.byteLength(updates.html, "utf-8") > this.config.maxFileSize) {
        throw new Error(`Canvas exceeds maximum size`);
      }
      canvas.html = this.sanitizeHTML(updates.html);
    }

    if (updates.appendHTML !== undefined) {
      // Smart append: insert before </body> if it exists, otherwise concat
      const newContent = canvas.html + updates.appendHTML;
      if (Buffer.byteLength(newContent, "utf-8") > this.config.maxFileSize) {
        throw new Error(`Canvas exceeds maximum size after append`);
      }

      if (canvas.html.includes("</body>")) {
        canvas.html = canvas.html.replace("</body>", `${updates.appendHTML}\n</body>`);
      } else {
        canvas.html = newContent;
      }
    }

    if (updates.title !== undefined) canvas.title = updates.title;
    if (updates.description !== undefined) canvas.description = updates.description;
    if (updates.tags !== undefined) canvas.tags = updates.tags;
    if (updates.public !== undefined) canvas.public = updates.public;

    canvas.updatedAt = new Date().toISOString();

    // Write to disk（原子写入，符合 AGENTS.md 规则）
    atomicWriteFileSync(this.getFilePath(id), canvas.html);
    canvases[index] = canvas;
    this.writeIndex(canvases);

    process.stdout.write(`[CanvasManager] Updated canvas "${id}"`);
    return canvas;
  }

  /** Delete a canvas */
  deleteCanvas(id: string): boolean {
    const canvases = this.readIndex();
    const index = canvases.findIndex((c) => c.id === id);
    if (index < 0) return false;

    canvases.splice(index, 1);
    this.writeIndex(canvases);

    const filePath = this.getFilePath(id);
    try {
      if (fs.existsSync(filePath)) fs.unlinkSync(filePath);
    } catch {
      // File might not exist
    }

    process.stdout.write(`[CanvasManager] Deleted canvas "${id}"`);
    return true;
  }

  /**
   * Create a canvas from the default template.
   * Useful when the agent wants a quick starting point.
   */
  createFromTemplate(
    title: string,
    replacements: Record<string, string> = {}
  ): { canvas: CanvasFile; url: string } {
    let html = CANVAS_TEMPLATE;
    html = html.replace("{{title}}", this.escapeHTML(title));
    html = html.replace(
      "{{timestamp}}",
      replacements.timestamp ?? new Date().toLocaleString()
    );

    for (const [key, value] of Object.entries(replacements)) {
      if (key === "title" || key === "timestamp") continue;
      html = html.replace(`{{${key}}}`, this.escapeHTML(value));
    }

    return this.createCanvas(title, html);
  }

  // ── Serving ─────────────────────────────────────────────────────────

  /**
   * Get the Content-Security-Policy header value for canvas pages.
   */
  getCSPHeader(): string {
    const cdnHosts = this.config.allowedCDNs.join(" ");
    return SANDBOX_POLICY.replace(
      /cdn\.jsdelivr\.net unpkg\.com cdnjs\.cloudflare\.com[^;]*;/g,
      `${cdnHosts};`
    );
  }

  // ── Helpers ─────────────────────────────────────────────────────────

  private getFilePath(id: string): string {
    // Sanitize id to prevent path traversal
    const safeId = id.replace(/[^a-zA-Z0-9_-]/g, "_");
    return path.join(this.config.storagePath, `${safeId}.html`);
  }

  private getFileSize(id: string): number {
    const filePath = this.getFilePath(id);
    try {
      return fs.existsSync(filePath) ? fs.statSync(filePath).size : 0;
    } catch {
      return 0;
    }
  }

  private readIndex(): CanvasFile[] {
    try {
      if (!fs.existsSync(this.indexPath)) return [];
      const raw = fs.readFileSync(this.indexPath, "utf-8");
      return JSON.parse(raw) as CanvasFile[];
    } catch {
      return [];
    }
  }

  private writeIndex(canvases: CanvasFile[]): void {
    try {
      atomicWriteFileSync(this.indexPath, JSON.stringify(canvases, null, 2));
    } catch (err) {
      process.stderr.write(`[CanvasManager] Failed to write index: ${err}`);
    }
  }

  private generateId(title: string): string {
    const slug = title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "")
      .slice(0, 40);
    const suffix = crypto.randomBytes(3).toString("hex");
    return `${slug}-${suffix}`;
  }

  private sanitizeHTML(html: string): string {
    // Inject CSP meta tag if not present
    if (!html.includes("Content-Security-Policy") && !html.includes("http-equiv")) {
      const cspMeta = `<meta http-equiv="Content-Security-Policy" content="${this.getCSPHeader()}">`;
      if (html.includes("<head>")) {
        html = html.replace("<head>", `<head>\n  ${cspMeta}`);
      } else if (html.includes("<html>")) {
        html = html.replace("<html>", `<html>\n<head>\n  ${cspMeta}\n</head>`);
      } else {
        html = `<!DOCTYPE html>\n<html>\n<head>\n  ${cspMeta}\n</head>\n<body>\n${html}\n</body>\n</html>`;
      }
    }
    return html;
  }

  private escapeHTML(str: string): string {
    return str
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#039;");
  }

  // ── Lifecycle ────────────────────────────────────────────────────────

  getStats(): { totalCanvases: number; storageUsedBytes: number; maxFiles: number } {
    const canvases = this.readIndex();
    const totalSize = canvases.reduce((sum, c) => sum + this.getFileSize(c.id), 0);
    return {
      totalCanvases: canvases.length,
      storageUsedBytes: totalSize,
      maxFiles: this.config.maxFiles,
    };
  }
}